services:
  - type: web
    name: harris-farm-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
    disk:
      name: hub-data
      mountPath: /data
      sizeGB: 10
